# Writes lib/config-win32.h: curl's CMake configuration for MSVC, the x64 and Win32 differences under _WIN64.
# Run from anywhere: cmake -P CMake/GenerateConfigWin32.cmake
set(root ${CMAKE_CURRENT_LIST_DIR}/..)
file(TO_CMAKE_PATH "$ENV{TEMP}/curl-config-win32" build)
foreach(arch x64 Win32)
  execute_process(COMMAND ${CMAKE_COMMAND} -S ${root} -B ${build}/${arch} -G "Visual Studio 18 2026" -A ${arch}
                  RESULT_VARIABLE result OUTPUT_QUIET)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "configuring curl for ${arch} failed")
  endif()
endforeach()

file(READ ${build}/x64/lib/curl_config.h config)
file(READ ${build}/Win32/lib/curl_config.h config32)
file(REMOVE_RECURSE ${build})
string(REPLACE "\r" "" config "${config}")
string(REPLACE "\r" "" config32 "${config32}")
string(REGEX MATCHALL "#define [A-Za-z0-9_]+[^\n]*" defines64 "${config}")
string(REGEX MATCHALL "#define [A-Za-z0-9_]+[^\n]*" defines32 "${config32}")
list(LENGTH defines64 count64)
list(LENGTH defines32 count32)
if(NOT count64 EQUAL count32)
  message(FATAL_ERROR "x64 defines ${count64} macros, Win32 ${count32}")
endif()
foreach(define32 IN LISTS defines32)
  string(REGEX REPLACE "#define ([A-Za-z0-9_]+).*" "\\1" name "${define32}")
  string(REGEX MATCH "#define ${name}( [^\n]*)?\n" define64 "${config}\n")
  string(STRIP "${define64}" define64)
  if(NOT define64)
    message(FATAL_ERROR "${name} is defined for Win32 only")
  endif()
  if(NOT define64 STREQUAL define32)
    string(REPLACE "${define64}" "#ifdef _WIN64\n${define64}\n#else\n${define32}\n#endif" config "${config}")
  endif()
endforeach()
file(CONFIGURE OUTPUT ${root}/lib/config-win32.h CONTENT "${config}" @ONLY NEWLINE_STYLE UNIX)
