# The mini fork's defaults: static libcurl, HTTP only, no tool, docs, install or optional libraries; Schannel on Windows
# and OpenSSL elsewhere. Normal variables stay in curl's directory scope and win over option() (CMP0077).
set(BUILD_SHARED_LIBS OFF)
set(BUILD_STATIC_LIBS ON)
set(BUILD_CURL_EXE OFF)
set(BUILD_EXAMPLES OFF)
set(BUILD_LIBCURL_DOCS OFF)
set(BUILD_MISC_DOCS OFF)
set(ENABLE_CURL_MANUAL OFF)
set(CURL_DISABLE_INSTALL ON)
set(CMAKE_DISABLE_FIND_PACKAGE_Perl ON)
set(PICKY_COMPILER OFF)
set(HTTP_ONLY ON)
set(USE_NGHTTP2 OFF)
set(USE_LIBIDN2 OFF)
set(CURL_USE_LIBPSL OFF)
set(CURL_USE_LIBSSH2 OFF)
set(CURL_USE_LIBSSH OFF)
set(CURL_USE_GSSAPI OFF)
if(WIN32)
  set(CURL_USE_SCHANNEL ON)
  set(CURL_USE_OPENSSL OFF)
else()
  set(CURL_USE_OPENSSL ON)
endif()
# curl_dependency_option() creates these as cache entries, which would drop a normal variable of the same name.
set(CURL_ZLIB OFF CACHE STRING "")
set(CURL_BROTLI OFF CACHE STRING "")
set(CURL_ZSTD OFF CACHE STRING "")
